# Generated by Django 3.2.4 on 2021-06-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencie', '0002_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=25),
        ),
    ]
