# Generated by Django 3.2.4 on 2021-06-05 20:33
import json
import os

from django.db import migrations

fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../fixtures'))
fixture_filename = 'cryptocurrencies.json'


def load_fixture(apps, schema_editor):
    cryptocurrency_model = apps.get_model('cryptocurrencie', 'Cryptocurrencie')

    fixture_file = os.path.join(fixture_dir, fixture_filename)
    fixture = open(fixture_file, 'r')

    cryptocurrencies = json.load(fixture)

    cryptocurrencies_lista = []

    for cryptocurrency in cryptocurrencies:
        abbreviation = cryptocurrency['abbreviation']
        name = cryptocurrency['name']

        cryptocurrencies_lista.append(
            cryptocurrency_model(
                name=name.strip(),
                abbreviation=abbreviation.strip()
            )
        )

    cryptocurrency_model.objects.bulk_create(cryptocurrencies_lista)


def reverte(apps, schema_editor):
    """
    Migration has no reversal
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencie', '0005_alter_cryptocurrencie_abbreviation'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverte),
    ]
