# Generated by Django 3.2.4 on 2021-06-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencie', '0002_wallet'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cryptocurrencies',
            field=models.ManyToManyField(through='cryptocurrencie.Wallet', to='cryptocurrencie.Cryptocurrencie'),
        ),
    ]
